import type { StateInstance, TofuPlan } from '@/widgets/iac-lab/model/types';

/**
 * Снятое настоящим OpenTofu для темы «Инфраструктура как код» — литералы, с которыми
 * `tests/unit/infrastructure-as-code.test.ts` сверяет учебный планировщик `PLAN_CODE`.
 * Файл собран из вывода самого теста (`IAC_DUMP=…`), руками не правился; как снято — в шапке
 * `data.ts`, раздел «Стенд». Состояния — из первого прогона (на их значения ссылаются тексты
 * темы), планы — из второго; планы двух прогонов совпали, это и сверяет часть теста с Docker.
 *
 * `STATE_COUNT` и `STATE_FOREACH` — `terraform.tfstate` после `tofu apply` сквозного примера
 * с `count` и с `for_each`, сжатые до формы планировщика: адрес экземпляра, поля `id`, `length`,
 * `special`, `result`, `input`, `output`, `filename`, `content` и `dependencies`.
 * У `terraform_data` поля `input`/`output` в состоянии лежат как `{ value, type }` — здесь
 * только `value`. Имя питомца, пароль и `id` случайны и при пересборке будут другими: тест
 * сверяет их тип, а не значение.
 *
 * `TOFU_PLANS` — по сценарию (`режим.правка.окружения.дрейф` и три `extra.*`):
 *   — `changes`: `resource_changes` из `tofu show -json tfplan` — адрес, `change.actions`,
 *     `action_reason`, `previous_address`, `replace_paths`;
 *   — `drift`: `resource_drift` оттуда же;
 *   — `edges`: граф apply из `tofu graph -plan=tfplan`, сведённый к шагам: `[зависимый, от кого]`,
 *     транзитивно через узлы `(expand)`, провайдеры и `local.*`; `(destroy deposed …)` записан
 *     как `(destroy)`;
 *   — `summary` и `headers`: строка `Plan: …` (или `No changes.`) и строки-заголовки
 *     экземпляров `# …` из текстового `tofu show tfplan`.
 */

export const STATE_COUNT: StateInstance[] = [
  {addr:"local_file.config",attrs:{id:"1c6cfc863f71720dbc2a1377dace06154dd5d9a9",filename:"out/app.conf",content:"app=cool-corgi\nrelease=v1\ndb_password=yZx5zg0EmvQjvOji\n"},deps:["random_password.db","random_pet.app","terraform_data.release"]},
  {addr:"local_file.env[0]",attrs:{id:"d8d51f5230722d3284facaef278d84831353cfdd",filename:"out/dev.txt",content:"env=dev\n"}},
  {addr:"local_file.env[1]",attrs:{id:"02988a0f90f5f8b05bab3c41ff9c7c169052cb25",filename:"out/stage.txt",content:"env=stage\n"}},
  {addr:"local_file.env[2]",attrs:{id:"5be83fac9c6118741d30d0d37cbf81ede959245b",filename:"out/prod.txt",content:"env=prod\n"}},
  {addr:"random_password.db",attrs:{id:"none",length:16,special:false,result:"yZx5zg0EmvQjvOji"}},
  {addr:"random_pet.app",attrs:{id:"cool-corgi",length:2}},
  {addr:"terraform_data.release",attrs:{id:"619c25a9-151b-c0aa-1f11-09623ecf9b01",input:"v1",output:"v1"}},
];

export const STATE_FOREACH: StateInstance[] = [
  {addr:"local_file.config",attrs:{id:"560f96b376ba37d05cf24696f517bd6e859935a3",filename:"out/app.conf",content:"app=destined-hookworm\nrelease=v1\ndb_password=vTuJmDAatTohFI58\n"},deps:["random_password.db","random_pet.app","terraform_data.release"]},
  {addr:"local_file.env[\"dev\"]",attrs:{id:"d8d51f5230722d3284facaef278d84831353cfdd",filename:"out/dev.txt",content:"env=dev\n"}},
  {addr:"local_file.env[\"prod\"]",attrs:{id:"5be83fac9c6118741d30d0d37cbf81ede959245b",filename:"out/prod.txt",content:"env=prod\n"}},
  {addr:"local_file.env[\"stage\"]",attrs:{id:"02988a0f90f5f8b05bab3c41ff9c7c169052cb25",filename:"out/stage.txt",content:"env=stage\n"}},
  {addr:"random_password.db",attrs:{id:"none",length:16,special:false,result:"vTuJmDAatTohFI58"}},
  {addr:"random_pet.app",attrs:{id:"destined-hookworm",length:2}},
  {addr:"terraform_data.release",attrs:{id:"393368c2-5849-af2c-b30e-4d2510caa2e2",input:"v1",output:"v1"}},
];

export const TOFU_PLANS: Record<string, TofuPlan> = {
  'count.none.all.clean': {
    summary: "No changes. Your infrastructure matches the configuration.",
    headers: [
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[0]",actions:["no-op"]},
      {addr:"local_file.env[1]",actions:["no-op"]},
      {addr:"local_file.env[2]",actions:["no-op"]},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
    ],
  },
  'count.none.all.drift': {
    summary: "Plan: 1 to add, 0 to change, 0 to destroy.",
    headers: [
      "# local_file.env[0] will be created",
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[0]",actions:["create"]},
      {addr:"local_file.env[1]",actions:["no-op"]},
      {addr:"local_file.env[2]",actions:["no-op"]},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[0]",actions:["delete"]}],
    edges: [
    ],
  },
  'count.none.drop.clean': {
    summary: "Plan: 1 to add, 0 to change, 2 to destroy.",
    headers: [
      "# local_file.env[1] must be replaced",
      "# local_file.env[2] will be destroyed",
      "# (because index [2] is out of range for count)",
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[0]",actions:["no-op"]},
      {addr:"local_file.env[1]",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content","filename"]},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_count_index"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
      ["local_file.env[1]","local_file.env[1] (destroy)"],
    ],
  },
  'count.none.drop.drift': {
    summary: "Plan: 2 to add, 0 to change, 2 to destroy.",
    headers: [
      "# local_file.env[0] will be created",
      "# local_file.env[1] must be replaced",
      "# local_file.env[2] will be destroyed",
      "# (because index [2] is out of range for count)",
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[0]",actions:["create"]},
      {addr:"local_file.env[1]",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content","filename"]},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_count_index"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[0]",actions:["delete"]}],
    edges: [
      ["local_file.env[1]","local_file.env[1] (destroy)"],
    ],
  },
  'count.input.all.clean': {
    summary: "Plan: 1 to add, 1 to change, 1 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[0]",actions:["no-op"]},
      {addr:"local_file.env[1]",actions:["no-op"]},
      {addr:"local_file.env[2]",actions:["no-op"]},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'count.input.all.drift': {
    summary: "Plan: 2 to add, 1 to change, 1 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[0] will be created",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[0]",actions:["create"]},
      {addr:"local_file.env[1]",actions:["no-op"]},
      {addr:"local_file.env[2]",actions:["no-op"]},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [{addr:"local_file.env[0]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'count.input.drop.clean': {
    summary: "Plan: 2 to add, 1 to change, 3 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[1] must be replaced",
      "# local_file.env[2] will be destroyed",
      "# (because index [2] is out of range for count)",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[0]",actions:["no-op"]},
      {addr:"local_file.env[1]",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content","filename"]},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_count_index"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["local_file.env[1]","local_file.env[1] (destroy)"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'count.input.drop.drift': {
    summary: "Plan: 3 to add, 1 to change, 3 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[0] will be created",
      "# local_file.env[1] must be replaced",
      "# local_file.env[2] will be destroyed",
      "# (because index [2] is out of range for count)",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[0]",actions:["create"]},
      {addr:"local_file.env[1]",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content","filename"]},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_count_index"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [{addr:"local_file.env[0]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["local_file.env[1]","local_file.env[1] (destroy)"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'count.force.all.clean': {
    summary: "Plan: 2 to add, 0 to change, 2 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[0]",actions:["no-op"]},
      {addr:"local_file.env[1]",actions:["no-op"]},
      {addr:"local_file.env[2]",actions:["no-op"]},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'count.force.all.drift': {
    summary: "Plan: 3 to add, 0 to change, 2 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[0] will be created",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[0]",actions:["create"]},
      {addr:"local_file.env[1]",actions:["no-op"]},
      {addr:"local_file.env[2]",actions:["no-op"]},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[0]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'count.force.drop.clean': {
    summary: "Plan: 3 to add, 0 to change, 4 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[1] must be replaced",
      "# local_file.env[2] will be destroyed",
      "# (because index [2] is out of range for count)",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[0]",actions:["no-op"]},
      {addr:"local_file.env[1]",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content","filename"]},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_count_index"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["local_file.env[1]","local_file.env[1] (destroy)"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'count.force.drop.drift': {
    summary: "Plan: 4 to add, 0 to change, 4 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[0] will be created",
      "# local_file.env[1] must be replaced",
      "# local_file.env[2] will be destroyed",
      "# (because index [2] is out of range for count)",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[0]",actions:["create"]},
      {addr:"local_file.env[1]",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content","filename"]},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_count_index"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[0]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["local_file.env[1]","local_file.env[1] (destroy)"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'for_each.none.all.clean': {
    summary: "No changes. Your infrastructure matches the configuration.",
    headers: [
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[\"dev\"]",actions:["no-op"]},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"]},
      {addr:"local_file.env[\"stage\"]",actions:["no-op"]},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
    ],
  },
  'for_each.none.all.drift': {
    summary: "Plan: 1 to add, 0 to change, 0 to destroy.",
    headers: [
      "# local_file.env[\"dev\"] will be created",
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"]},
      {addr:"local_file.env[\"stage\"]",actions:["no-op"]},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[\"dev\"]",actions:["delete"]}],
    edges: [
    ],
  },
  'for_each.none.drop.clean': {
    summary: "Plan: 0 to add, 0 to change, 1 to destroy.",
    headers: [
      "# local_file.env[\"stage\"] will be destroyed",
      "# (because key [\"stage\"] is not in for_each map)",
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[\"dev\"]",actions:["no-op"]},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"]},
      {addr:"local_file.env[\"stage\"]",actions:["delete"],reason:"delete_because_each_key"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
    ],
  },
  'for_each.none.drop.drift': {
    summary: "Plan: 1 to add, 0 to change, 1 to destroy.",
    headers: [
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"stage\"] will be destroyed",
      "# (because key [\"stage\"] is not in for_each map)",
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"]},
      {addr:"local_file.env[\"stage\"]",actions:["delete"],reason:"delete_because_each_key"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[\"dev\"]",actions:["delete"]}],
    edges: [
    ],
  },
  'for_each.input.all.clean': {
    summary: "Plan: 1 to add, 1 to change, 1 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["no-op"]},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"]},
      {addr:"local_file.env[\"stage\"]",actions:["no-op"]},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'for_each.input.all.drift': {
    summary: "Plan: 2 to add, 1 to change, 1 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[\"dev\"] will be created",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"]},
      {addr:"local_file.env[\"stage\"]",actions:["no-op"]},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [{addr:"local_file.env[\"dev\"]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'for_each.input.drop.clean': {
    summary: "Plan: 1 to add, 1 to change, 2 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[\"stage\"] will be destroyed",
      "# (because key [\"stage\"] is not in for_each map)",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["no-op"]},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"]},
      {addr:"local_file.env[\"stage\"]",actions:["delete"],reason:"delete_because_each_key"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'for_each.input.drop.drift': {
    summary: "Plan: 2 to add, 1 to change, 2 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"stage\"] will be destroyed",
      "# (because key [\"stage\"] is not in for_each map)",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"]},
      {addr:"local_file.env[\"stage\"]",actions:["delete"],reason:"delete_because_each_key"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [{addr:"local_file.env[\"dev\"]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'for_each.force.all.clean': {
    summary: "Plan: 2 to add, 0 to change, 2 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["no-op"]},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"]},
      {addr:"local_file.env[\"stage\"]",actions:["no-op"]},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'for_each.force.all.drift': {
    summary: "Plan: 3 to add, 0 to change, 2 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[\"dev\"] will be created",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"]},
      {addr:"local_file.env[\"stage\"]",actions:["no-op"]},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[\"dev\"]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'for_each.force.drop.clean': {
    summary: "Plan: 2 to add, 0 to change, 3 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[\"stage\"] will be destroyed",
      "# (because key [\"stage\"] is not in for_each map)",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["no-op"]},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"]},
      {addr:"local_file.env[\"stage\"]",actions:["delete"],reason:"delete_because_each_key"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'for_each.force.drop.drift': {
    summary: "Plan: 3 to add, 0 to change, 3 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"stage\"] will be destroyed",
      "# (because key [\"stage\"] is not in for_each map)",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"]},
      {addr:"local_file.env[\"stage\"]",actions:["delete"],reason:"delete_because_each_key"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[\"dev\"]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'migrate.none.all.clean': {
    summary: "Plan: 3 to add, 0 to change, 3 to destroy.",
    headers: [
      "# local_file.env[0] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[1] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[2] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"prod\"] will be created",
      "# local_file.env[\"stage\"] will be created",
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["create"]},
      {addr:"local_file.env[\"stage\"]",actions:["create"]},
      {addr:"local_file.env[0]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[1]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
    ],
  },
  'migrate.none.all.drift': {
    summary: "Plan: 3 to add, 0 to change, 2 to destroy.",
    headers: [
      "# local_file.env[1] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[2] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"prod\"] will be created",
      "# local_file.env[\"stage\"] will be created",
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["create"]},
      {addr:"local_file.env[\"stage\"]",actions:["create"]},
      {addr:"local_file.env[1]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[0]",actions:["delete"]}],
    edges: [
    ],
  },
  'migrate.none.drop.clean': {
    summary: "Plan: 2 to add, 0 to change, 3 to destroy.",
    headers: [
      "# local_file.env[0] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[1] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[2] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"prod\"] will be created",
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["create"]},
      {addr:"local_file.env[0]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[1]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
    ],
  },
  'migrate.none.drop.drift': {
    summary: "Plan: 2 to add, 0 to change, 2 to destroy.",
    headers: [
      "# local_file.env[1] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[2] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"prod\"] will be created",
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["create"]},
      {addr:"local_file.env[1]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[0]",actions:["delete"]}],
    edges: [
    ],
  },
  'migrate.input.all.clean': {
    summary: "Plan: 4 to add, 1 to change, 4 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[0] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[1] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[2] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"prod\"] will be created",
      "# local_file.env[\"stage\"] will be created",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["create"]},
      {addr:"local_file.env[\"stage\"]",actions:["create"]},
      {addr:"local_file.env[0]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[1]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'migrate.input.all.drift': {
    summary: "Plan: 4 to add, 1 to change, 3 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[1] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[2] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"prod\"] will be created",
      "# local_file.env[\"stage\"] will be created",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["create"]},
      {addr:"local_file.env[\"stage\"]",actions:["create"]},
      {addr:"local_file.env[1]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [{addr:"local_file.env[0]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'migrate.input.drop.clean': {
    summary: "Plan: 3 to add, 1 to change, 4 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[0] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[1] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[2] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"prod\"] will be created",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["create"]},
      {addr:"local_file.env[0]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[1]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'migrate.input.drop.drift': {
    summary: "Plan: 3 to add, 1 to change, 3 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[1] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[2] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"prod\"] will be created",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["create"]},
      {addr:"local_file.env[1]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [{addr:"local_file.env[0]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'migrate.force.all.clean': {
    summary: "Plan: 5 to add, 0 to change, 5 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[0] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[1] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[2] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"prod\"] will be created",
      "# local_file.env[\"stage\"] will be created",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["create"]},
      {addr:"local_file.env[\"stage\"]",actions:["create"]},
      {addr:"local_file.env[0]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[1]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'migrate.force.all.drift': {
    summary: "Plan: 5 to add, 0 to change, 4 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[1] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[2] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"prod\"] will be created",
      "# local_file.env[\"stage\"] will be created",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["create"]},
      {addr:"local_file.env[\"stage\"]",actions:["create"]},
      {addr:"local_file.env[1]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[0]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'migrate.force.drop.clean': {
    summary: "Plan: 4 to add, 0 to change, 5 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[0] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[1] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[2] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"prod\"] will be created",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["create"]},
      {addr:"local_file.env[0]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[1]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'migrate.force.drop.drift': {
    summary: "Plan: 4 to add, 0 to change, 4 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[1] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[2] will be destroyed",
      "# (because resource does not use count)",
      "# local_file.env[\"dev\"] will be created",
      "# local_file.env[\"prod\"] will be created",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"]},
      {addr:"local_file.env[\"prod\"]",actions:["create"]},
      {addr:"local_file.env[1]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_wrong_repetition"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[0]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'moved.none.all.clean': {
    summary: "Plan: 0 to add, 0 to change, 0 to destroy.",
    headers: [
      "# local_file.env[0] has moved to local_file.env[\"dev\"]",
      "# local_file.env[2] has moved to local_file.env[\"prod\"]",
      "# local_file.env[1] has moved to local_file.env[\"stage\"]",
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[\"dev\"]",actions:["no-op"],previous:"local_file.env[0]"},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"],previous:"local_file.env[2]"},
      {addr:"local_file.env[\"stage\"]",actions:["no-op"],previous:"local_file.env[1]"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
    ],
  },
  'moved.none.all.drift': {
    summary: "Plan: 1 to add, 0 to change, 0 to destroy.",
    headers: [
      "# local_file.env[\"dev\"] will be created",
      "# (moved from local_file.env[0])",
      "# local_file.env[2] has moved to local_file.env[\"prod\"]",
      "# local_file.env[1] has moved to local_file.env[\"stage\"]",
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"],previous:"local_file.env[0]"},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"],previous:"local_file.env[2]"},
      {addr:"local_file.env[\"stage\"]",actions:["no-op"],previous:"local_file.env[1]"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[\"dev\"]",actions:["delete"]}],
    edges: [
    ],
  },
  'moved.none.drop.clean': {
    summary: "Plan: 0 to add, 0 to change, 1 to destroy.",
    headers: [
      "# local_file.env[0] has moved to local_file.env[\"dev\"]",
      "# local_file.env[2] has moved to local_file.env[\"prod\"]",
      "# local_file.env[\"stage\"] will be destroyed",
      "# (because key [\"stage\"] is not in for_each map)",
      "# (moved from local_file.env[1])",
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[\"dev\"]",actions:["no-op"],previous:"local_file.env[0]"},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"],previous:"local_file.env[2]"},
      {addr:"local_file.env[\"stage\"]",actions:["delete"],reason:"delete_because_each_key",previous:"local_file.env[1]"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
    ],
  },
  'moved.none.drop.drift': {
    summary: "Plan: 1 to add, 0 to change, 1 to destroy.",
    headers: [
      "# local_file.env[\"dev\"] will be created",
      "# (moved from local_file.env[0])",
      "# local_file.env[2] has moved to local_file.env[\"prod\"]",
      "# local_file.env[\"stage\"] will be destroyed",
      "# (because key [\"stage\"] is not in for_each map)",
      "# (moved from local_file.env[1])",
    ],
    changes: [
      {addr:"local_file.config",actions:["no-op"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"],previous:"local_file.env[0]"},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"],previous:"local_file.env[2]"},
      {addr:"local_file.env[\"stage\"]",actions:["delete"],reason:"delete_because_each_key",previous:"local_file.env[1]"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[\"dev\"]",actions:["delete"]}],
    edges: [
    ],
  },
  'moved.input.all.clean': {
    summary: "Plan: 1 to add, 1 to change, 1 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[0] has moved to local_file.env[\"dev\"]",
      "# local_file.env[2] has moved to local_file.env[\"prod\"]",
      "# local_file.env[1] has moved to local_file.env[\"stage\"]",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["no-op"],previous:"local_file.env[0]"},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"],previous:"local_file.env[2]"},
      {addr:"local_file.env[\"stage\"]",actions:["no-op"],previous:"local_file.env[1]"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'moved.input.all.drift': {
    summary: "Plan: 2 to add, 1 to change, 1 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[\"dev\"] will be created",
      "# (moved from local_file.env[0])",
      "# local_file.env[2] has moved to local_file.env[\"prod\"]",
      "# local_file.env[1] has moved to local_file.env[\"stage\"]",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"],previous:"local_file.env[0]"},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"],previous:"local_file.env[2]"},
      {addr:"local_file.env[\"stage\"]",actions:["no-op"],previous:"local_file.env[1]"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [{addr:"local_file.env[\"dev\"]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'moved.input.drop.clean': {
    summary: "Plan: 1 to add, 1 to change, 2 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[0] has moved to local_file.env[\"dev\"]",
      "# local_file.env[2] has moved to local_file.env[\"prod\"]",
      "# local_file.env[\"stage\"] will be destroyed",
      "# (because key [\"stage\"] is not in for_each map)",
      "# (moved from local_file.env[1])",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["no-op"],previous:"local_file.env[0]"},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"],previous:"local_file.env[2]"},
      {addr:"local_file.env[\"stage\"]",actions:["delete"],reason:"delete_because_each_key",previous:"local_file.env[1]"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'moved.input.drop.drift': {
    summary: "Plan: 2 to add, 1 to change, 2 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[\"dev\"] will be created",
      "# (moved from local_file.env[0])",
      "# local_file.env[2] has moved to local_file.env[\"prod\"]",
      "# local_file.env[\"stage\"] will be destroyed",
      "# (because key [\"stage\"] is not in for_each map)",
      "# (moved from local_file.env[1])",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"],previous:"local_file.env[0]"},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"],previous:"local_file.env[2]"},
      {addr:"local_file.env[\"stage\"]",actions:["delete"],reason:"delete_because_each_key",previous:"local_file.env[1]"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [{addr:"local_file.env[\"dev\"]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
    ],
  },
  'moved.force.all.clean': {
    summary: "Plan: 2 to add, 0 to change, 2 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[0] has moved to local_file.env[\"dev\"]",
      "# local_file.env[2] has moved to local_file.env[\"prod\"]",
      "# local_file.env[1] has moved to local_file.env[\"stage\"]",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["no-op"],previous:"local_file.env[0]"},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"],previous:"local_file.env[2]"},
      {addr:"local_file.env[\"stage\"]",actions:["no-op"],previous:"local_file.env[1]"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'moved.force.all.drift': {
    summary: "Plan: 3 to add, 0 to change, 2 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[\"dev\"] will be created",
      "# (moved from local_file.env[0])",
      "# local_file.env[2] has moved to local_file.env[\"prod\"]",
      "# local_file.env[1] has moved to local_file.env[\"stage\"]",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"],previous:"local_file.env[0]"},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"],previous:"local_file.env[2]"},
      {addr:"local_file.env[\"stage\"]",actions:["no-op"],previous:"local_file.env[1]"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[\"dev\"]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'moved.force.drop.clean': {
    summary: "Plan: 2 to add, 0 to change, 3 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[0] has moved to local_file.env[\"dev\"]",
      "# local_file.env[2] has moved to local_file.env[\"prod\"]",
      "# local_file.env[\"stage\"] will be destroyed",
      "# (because key [\"stage\"] is not in for_each map)",
      "# (moved from local_file.env[1])",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["no-op"],previous:"local_file.env[0]"},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"],previous:"local_file.env[2]"},
      {addr:"local_file.env[\"stage\"]",actions:["delete"],reason:"delete_because_each_key",previous:"local_file.env[1]"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'moved.force.drop.drift': {
    summary: "Plan: 3 to add, 0 to change, 3 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[\"dev\"] will be created",
      "# (moved from local_file.env[0])",
      "# local_file.env[2] has moved to local_file.env[\"prod\"]",
      "# local_file.env[\"stage\"] will be destroyed",
      "# (because key [\"stage\"] is not in for_each map)",
      "# (moved from local_file.env[1])",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[\"dev\"]",actions:["create"],previous:"local_file.env[0]"},
      {addr:"local_file.env[\"prod\"]",actions:["no-op"],previous:"local_file.env[2]"},
      {addr:"local_file.env[\"stage\"]",actions:["delete"],reason:"delete_because_each_key",previous:"local_file.env[1]"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [{addr:"local_file.env[\"dev\"]",actions:["delete"]}],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","random_pet.app (destroy)"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app","local_file.config (destroy)"],
      ["random_pet.app","random_pet.app (destroy)"],
    ],
  },
  'extra.cbd': {
    summary: "Plan: 2 to add, 0 to change, 2 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# random_pet.app must be replaced",
    ],
    changes: [
      {addr:"local_file.config",actions:["create","delete"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[0]",actions:["no-op"]},
      {addr:"local_file.env[1]",actions:["no-op"]},
      {addr:"local_file.env[2]",actions:["no-op"]},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["create","delete"],reason:"replace_because_cannot_update",replacePaths:["length"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
      ["local_file.config (destroy)","local_file.config"],
      ["local_file.config (destroy)","random_pet.app"],
      ["local_file.config","random_pet.app"],
      ["random_pet.app (destroy)","local_file.config (destroy)"],
      ["random_pet.app (destroy)","local_file.config"],
      ["random_pet.app (destroy)","random_pet.app"],
    ],
  },
  'extra.depends': {
    summary: "Plan: 2 to add, 1 to change, 3 to destroy.",
    headers: [
      "# local_file.config must be replaced",
      "# local_file.env[1] must be replaced",
      "# local_file.env[2] will be destroyed",
      "# (because index [2] is out of range for count)",
      "# terraform_data.release will be updated in-place",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content"]},
      {addr:"local_file.env[0]",actions:["no-op"]},
      {addr:"local_file.env[1]",actions:["delete","create"],reason:"replace_because_cannot_update",replacePaths:["content","filename"]},
      {addr:"local_file.env[2]",actions:["delete"],reason:"delete_because_count_index"},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["update"]},
    ],
    drift: [],
    edges: [
      ["local_file.config","local_file.config (destroy)"],
      ["local_file.config","local_file.env[1] (destroy)"],
      ["local_file.config","terraform_data.release"],
      ["local_file.env[1]","local_file.config (destroy)"],
      ["local_file.env[1]","local_file.env[1] (destroy)"],
      ["local_file.env[1]","terraform_data.release"],
      ["terraform_data.release","local_file.config (destroy)"],
      ["terraform_data.release","local_file.env[1] (destroy)"],
    ],
  },
  'extra.removed': {
    summary: "Plan: 0 to add, 0 to change, 1 to destroy.",
    headers: [
      "# local_file.config will be destroyed",
      "# (because local_file.config is not in configuration)",
    ],
    changes: [
      {addr:"local_file.config",actions:["delete"],reason:"delete_because_no_resource_config"},
      {addr:"local_file.env[0]",actions:["no-op"]},
      {addr:"local_file.env[1]",actions:["no-op"]},
      {addr:"local_file.env[2]",actions:["no-op"]},
      {addr:"random_password.db",actions:["no-op"]},
      {addr:"random_pet.app",actions:["no-op"]},
      {addr:"terraform_data.release",actions:["no-op"]},
    ],
    drift: [],
    edges: [
    ],
  },
};
